apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    app: spark-master
  ports:
  - name: web-ui
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: master
    protocol: TCP                                                                                                                                                                                                                           
    port: 7077
    targetPort: 7077
  - name: master-rest
    protocol: TCP                                                                                                                                                                                                                           
    port: 6066
    targetPort: 6066
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: spark-client
spec:
  selector:
    app: spark-client
  clusterIP: None
---
apiVersion: apps/v1                                                                                                                                                                                                                         
kind: Deployment                                                                                                                                                                                                                            
metadata:                                                                                                                                                                                                                                   
  name: spark-master                                                                                                                                                                                                                        
  labels:                                                                                                                                                                                                                                   
    app: spark-master                                                                                                                                                                                                                       
spec:                                                                                                                                                                                                                                       
  selector:                                                                                                                                                                                                                                 
    matchLabels:                                                                                                                                                                                                                            
      app: spark-master                                                                                                                                                                                                                     
  template:                                                                                                                                                                                                                                 
    metadata:                                                                                                                                                                                                                               
      labels:                                                                                                                                                                                                                               
        app: spark-master                                                                                                                                                                                                                   
    spec:                                                                                                                                                                                                                                   
      containers:                                                                                                                                                                                                                           
      - name: spark-master                                                                                                                                                                                                                  
        image: ajgrande924/spark-master:latest
        # image: bde2020/spark-master:2.4.3-hadoop2.7                                                                                                                                                                                         
        imagePullPolicy: Always
        ports:                                                                                                                                                                                                                              
        - containerPort: 8080                                                                                                                                                                                                               
        - containerPort: 7077                                                                                                                                                                                                               
        - containerPort: 6066
        env: 
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: scale-secret
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: scale-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: scale-secret
                key: POSTGRES_PASSWORD 
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: scale-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: scale-secret
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_DEFAULT_REGION
            valueFrom:
              secretKeyRef:
                name: scale-secret
                key: AWS_DEFAULT_REGION                                                                                                                                                                                                          
---                                                                                                                                                                                                                                         
apiVersion: apps/v1                                                                                                                                                                                                                         
kind: DaemonSet                                                                                                                                                                                                                             
metadata:
  name: spark-worker
  labels:
    app: spark-worker
spec:
  selector:
    matchLabels:
      name: spark-worker
  template:
    metadata:
      labels:
        name: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: ajgrande924/spark-worker:latest
        # image: bde2020/spark-worker:2.4.3-hadoop2.7
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env: 
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: scale-secret
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: scale-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: scale-secret
                key: POSTGRES_PASSWORD 
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: scale-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: scale-secret
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_DEFAULT_REGION
            valueFrom:
              secretKeyRef:
                name: scale-secret
                key: AWS_DEFAULT_REGION
